---
title: Docker Set Up
subtitle: Instructions on installing and setting up Docker
date: ""
author: ""
code-tools: false
format: html
engine: knitr
---

## Install Docker

Ensure that you install Docker or Docker Desktop before the course starts. If you do not have admin rights to install software on your laptop, talk to your local IT for help.

### {{< fa brands ubuntu >}} Linux

Follow the installation instructions for your OS:

  - [Ubuntu](https://docs.docker.com/install/linux/docker-ce/ubuntu/)
  - [Debian](https://docs.docker.com/install/linux/docker-ce/debian/)
  - [Fedora](https://docs.docker.com/install/linux/docker-ce/fedora/)

After Docker Desktop starts, open the Dashboard and go to *Settings ({{< fa gear >}} in the top-right) > General*. Follow the [instructions](https://docs.docker.com/desktop/settings/linux/) in the _General_ section.

### {{< fa brands apple >}} Mac

Visit [this page](https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install) to ensure you have the requirements necessary.

Download [Docker Desktop for Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac) with _Apple Silicon_ or _Intel Chip_ and follow the installation instructions.

After Docker Desktop starts, open the Dashboard and go to *Settings ({{< fa gear >}} in the top-right) > General*. Follow the [instructions](https://docs.docker.com/desktop/settings/mac/) in the _General_ section.

::: {.callout-important}
On Mac M1/M2/M3, in Docker Settings > General, check **Use Rosetta for x86/amd64 emulation on Apple Silicon**.
:::

### {{< fa brands windows >}} Windows

Visit [this page](https://docs.docker.com/desktop/install/windows-install/) to ensure you have the requirements necessary.

Download [Docker Desktop for Windows](https://hub.docker.com/editions/community/docker-ce-desktop-windows) and follow the installation instructions. 

After Docker Desktop starts, open the Dashboard and go to *Settings ({{< fa gear >}} in the top-right) > General*. Follow the [instructions](https://docs.docker.com/desktop/settings/windows//) in the _General_ section.

After installation, open a PowerShell terminal and try to run `docker --version`. If that works, Docker is set up.

## Test installation

From the terminal, type:

```bash
docker --version
```

and then run your first image by typing:

```bash
docker run hello-world
```

If both work as expected, you successfully installed Docker Desktop!

## Allocate resources 

Open the Docker Dashboard when Docker Desktop starts and go to *Settings ({{< fa gear >}} in the top-right) > Resources* to allocate the following resources: 

  - **CPU limit**: `8`  
  - **Memory limit**: `12 GB`  
  - **Swap**: `2 GB`  

On Windows, if WSL engine is used, you might not be able to change resources directly.
