title: "Single_cell RNA sequencing analysis course"
baseurl: /workshop-scRNAseq

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url:
  - title: Schedule
    url: schedule
  - title: Exercises
    url: exercises
  - title: Pre-course
    url: precourse
  - title: FAQ
    url: labs/FAQ
  - title: Travel info
    url: travel
