---
title: "Precourse"
subtitle: "These are steps to be completed before the workshop"
description: ""
date: ""
author: ""
sidebar: false
code-tools: false
format: html
---

```{r}
#| include: false
library(yaml)
library(here)
upid <- yaml::read_yaml(here("_quarto.yml"))$uppmax_project
upstore <- yaml::read_yaml(here("_quarto.yml"))$uppmax_storage
```

## Knowledge Requirements

We strongly recommend for those not yet familiar with UNIX and/or R/Python to take this opportunity and take these online tutorials, since **those are requirements for the workshop**. This will help you to develop your programming skills and we can always learn a few tricks here and there, even if you are already experienced.

- UNIX (part_1): [http://swcarpentry.github.io/shell-novice/](http://swcarpentry.github.io/shell-novice/)
- UNIX (part_2): [https://carpentries-incubator.github.io/shell-extras/](https://carpentries-incubator.github.io/shell-extras/)
- R (part_1): [https://swcarpentry.github.io/r-novice-inflammation/](https://swcarpentry.github.io/r-novice-inflammation/)
- R (part_2): [http://swcarpentry.github.io/r-novice-gapminder/](http://swcarpentry.github.io/r-novice-gapminder/)
- Python (part_1):[https://swcarpentry.github.io/python-novice-inflammation/](https://swcarpentry.github.io/python-novice-inflammation/)
- Python (part_2): [http://swcarpentry.github.io/python-novice-gapminder/](http://swcarpentry.github.io/python-novice-gapminder/)

After taking those courses (or any other equivalent course in programming in bash and R or Python) will provide you with the basics in, for example:

- file structure and manipulation in bash
- loading, handling and manipulating vectors, matrices, factors and lists
- creating for-loops
- using Rmarkdown/Jupyter for reports
- editing and writing files in the command line
- and much more ...

## Slack

Make sure that you have [**Slack**](https://slack.com/intl/en-se/downloads) installed because we will use it a lot during the workshop. Communication, troubleshooting and group discussions will happen via **Slack workspace** `NBIS-workshop-RNAseq`. All accepted students will receive an invitation link via email. Please add this workspace to your Slack application on your desktop and **NOT** use it in the web.

Please join the following channels once you are in the workspace:

- `#software-to-install` for questions about installation and troubleshooting
- `#general` for general questions about the workshop

::: {.callout-note}
Please post your question in the channel and **NOT** directly to the teacher. Any participant that knows the answer to any problem is encouraged to help too.
:::

## Uppmax

We will use the high performance computing cluster (HPC) UPPMAX for the workshop. You will need to create accounts if you don't already have one. And you will need to join the course project. See instructions [here](other/uppmax.qmd).

## Docker/Singularity

A Docker/Singularity container allows you to reproducible the results using the same versions of tools as we use on the workshop. To setup / use docker, see [here](other/docker.qmd).

## Conda (Optional)

A Conda environment allows you to reproducible the results using the same versions of tools as we use on the workshop. Download the conda environment here.

<a class="btn btn-secondary" href="other/conda.yml" role="button">conda.yml {{< fa download >}}</a>

For conda setup and usage instructions, see [here](other/conda.html).

## Datasets

Datasets for this workshop are hosted on an instance of Figshare.

## FAQ

Please refer to the [FAQ](other/faq.html) for troubleshooting common issues.
