---
title: "Syllabus"
subtitle: "This workshop is aimed towards researchers who want to start analyzing single cell rna-seq data."
date: ""
author: ""
toc: false
number-sections: false
sidebar: false
code-tools: false
format: html
---

::: {.panel-tabset}

## Syllabus

This workshop will cover the basic steps in single cell RNAseq (scRNAseq) processing and data analysis, with lectures and practical exercises. 

Topics covered will include:

- Overview of the current scRNAseq technologies
- Raw reads into expression values
- Quality control of scRNAseq data
- Dimensionality reduction and clustering techniques
- Data normalization
- Differential gene expression for scRNAseq data
- Celltype prediction
- Trajectory analysis
- Comparison of sc analysis toolkits: Seurat, Bioconductor and Scanpy

## Who can apply?

- This is a national workshop open for PhD students, postdocs, group leaders and core facility staff within all Swedish universities. We do accept application from other countries, but priority is given to applicants from Swedish universities prior to applicants from industry and academics from other countries.  
- Please note that NBIS training events do not provide any formal university credits. The training content is estimated to correspond to a certain number of credits, however the estimated credits are just guidelines. If formal credits are crucial, the student needs to confer with the home department before submitting a workshop application in order to establish whether the workshop is valid for formal credits or not.  
- We cannot invoice private individuals, therefore an affiliation is required.

## Entry requirements

Practical exercises can be performed using R or Python, so we only accept students with previous experience in one of those programming languages.

- Basic knowledge in R/Python and command line (bash).
- Be able to use your own computer with R or Python installed for the practical computational exercises. Instructions on installation will be sent by email to accepted participants.
- Programming/scripting experience is required (in R or python).
- Basic understanding of NGS technologies and RNA-sequencing data.

- **Desirable**: Previous experience with RNA-seq analysis and/or participation in NGS/RNA-seq workshop is an advantage.

Due to limited space the workshop can accommodate maximum of 25 participants. If we receive more applications, participants will be selected based on several criteria. Selection criteria include correct entry requirements, motivation to attend the workshop as well as gender and geographical balance.

:::
