---
title: "Scater/Scran: Dimensionality reduction"
#CSS_ALL:
---

#DIMRED_TITLE:

#DIMRED_ALL1:

```{r, message='hide',warning='hide',results='hold'}
suppressMessages(require(scater))
suppressMessages(require(scran))
suppressMessages(require(cowplot))
suppressMessages(require(cowplot))
suppressMessages(require(ggplot2))
suppressMessages(require(rafalib))

sce <- readRDS("data/3pbmc_qc.rds")
```

#DIMRED_ALL1.1:

#DIMRED_ALL2:

```{r, message='hide',warning='hide',results='hold'}
sce <- computeSumFactors(sce, sizes=c(20, 40, 60, 80))
sce <- normalize(sce)
var.fit <- trendVar(sce, use.spikes=FALSE,method="loess",loess.args=list(span=0.02))
var.out <- decomposeVar(sce, var.fit)

mypar(1,2)
#plot mean over TOTAL variance
plot(var.out$mean, var.out$total, pch=16, cex=0.4, xlab="Mean log-expression",
     ylab="Variance of log-expression")
o <- order(var.out$mean)
lines(var.out$mean[o], var.out$tech[o], col="dodgerblue", lwd=2)
cutoff <- var.out$bio > 0.15
points(var.out$mean[cutoff], var.out$total[cutoff], col="red", pch=16,cex=.6)

#plot mean over BIOLOGICAL variance
plot(var.out$mean, var.out$bio, pch=16, cex=0.4, xlab="Mean log-expression",
     ylab="Variance of log-expression")
lines(c(min(var.out$mean),max(var.out$mean)), c(0,0), col="dodgerblue", lwd=2)
points(var.out$mean[cutoff], var.out$bio[cutoff], col="red", pch=16,cex=.6)

hvg.out <- var.out[which(var.out$FDR <= 0.05 & var.out$bio >= 0.5),]
hvg.out <- hvg.out[order(hvg.out$bio, decreasing=TRUE),]
nrow(hvg.out)
```

#DIMRED_ALL3:

#DIMRED_ALL4:

```{r, message='hide',warning='hide',results='hold'}
norm.exprs <- exprs(sce)[rownames(hvg.out),,drop=FALSE]
```


***
#PCA_TITLE:

#PCA_ALL1:

```{r, message='hide',warning='hide',results='hold'}
sce <- runPCA(sce, exprs_values = logcounts, ncomponents = 30, feature_set = rownames(hvg.out), scale_features = T)
```

#PCA_ALL2:

```{r, message='hide',warning='hide',results='hold',fig.asp=.28,fig.width=16}
plot_grid(ncol = 3,
  plotReducedDim(sce,use_dimred = "PCA",colour_by = "sample_id",ncomponents = 1:2),
  plotReducedDim(sce,use_dimred = "PCA",colour_by = "sample_id",ncomponents = 3:4),
  plotReducedDim(sce,use_dimred = "PCA",colour_by = "sample_id",ncomponents = 5:6) )

```

#PCA_ALL3:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.4,fig.width=12}
plot_grid(ncol = 2, 
          plotExplanatoryPCs(sce),
          plotExplanatoryVariables(sce))

```

#PCA_ALL4:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.3,fig.width=12}

```

#PCA_ALL5:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.7,fig.width=4}
mypar()
plot(attr(sce@reducedDims$PCA,"percentVar")[1:50]*100,type="l",ylab="% variance",xlab="Principal component #")
points(attr(sce@reducedDims$PCA,"percentVar")[1:50]*100,pch=21,bg="grey",cex=.5)
```

#PCA_ALL6:

***
#tSNE_TITLE:

#tSNE_ALL1:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=1,fig.width=5}
sce <- runTSNE(sce, use_dimred = "PCA", n_dimred = 30, 
               perplexity = 30,
               rand_seed = 42)
#see ?Rtsne and ?runTSNE for more info
```

#tSNE_ALL2:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.28,fig.width=16}
plot_grid(ncol = 3,plotReducedDim(sce,use_dimred = "TSNE",colour_by = "sample_id"))
```


***
#UMAP_TITLE:

#UMAP_ALL1:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=1.2,fig.width=10}
sce <- runUMAP(sce,use_dimred = "PCA", n_dimred = 30,   ncomponents = 2)
#see ?umap and ?runUMAP for more info
```

#UMAP_ALL2:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.28,fig.width=16}
plot_grid(ncol = 3,plotReducedDim(sce,use_dimred = "UMAP",colour_by = "sample_id"))
```

***
#DIMRED_TITLE2:

#DIMRED_ALL5:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.28,fig.width=10}
plot_grid(ncol = 3,
  plotReducedDim(sce,use_dimred = "PCA",colour_by = "sample_id"),
  plotReducedDim(sce,use_dimred = "TSNE",colour_by = "sample_id"),
  plotReducedDim(sce,use_dimred = "UMAP",colour_by = "sample_id")
)
```

#DIMRED_ALL6:

#MARKER_TABLE:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.asp=.65,fig.width=10}
plotlist <- list()
for(i in c("CD3E","CD4","CD8A","NKG7","GNLY","MS4A1","CD14","LYZ","MS4A7","FCGR3A","CST3","FCER1A")){
plotlist[[i]] <-plotReducedDim(sce,use_dimred = "UMAP",colour_by = i,by_exprs_values = "logcounts") + scale_fill_gradientn(colours = colorRampPalette(c("grey90","orange3","firebrick","firebrick","red","red" ))(10)) + ggtitle(label = i)+ theme(plot.title = element_text(size=20)) }
plot_grid(ncol=4, plotlist = plotlist)

```


#DIMRED_ALL7:

```{r,message='hide',warning='hide', results='hold',results='hold',fig.height=5,fig.width=16}
saveRDS(sce,"data/3pbmc_qc_dm.rds")
```


















