---
#CSS_ALL:
editor_options:
  chunk_output_type: console
---

#CHUNK_OPT:

#CLUST_TITLE:

#CLUST_ALL:

#CLUST_ALL2:

```{r, message='hide',warning='hide',results='hold'}

suppressPackageStartupMessages({
  library(Seurat)
  library(cowplot)
  library(ggplot2)
  library(pheatmap)
  library(rafalib)
  library(clustree)
})

alldata <- readRDS("data/results/covid_qc_dr_int.rds")
```

#CLUST_TITLE2:

#CLUST_ALL3:

#CLUST_TITLE2.1:

#CLUST_ALL4:

#CLUST_SEURAT:

```{r, message='hide',warning='hide',results='hold'}
# check that CCA is still the active assay
alldata@active.assay


alldata <- FindNeighbors(alldata,
                         dims = 1:30,
                         k.param = 60,
                         prune.SNN = 1/15)

# check the names for graphs in the object.
names(alldata@graphs)
```

#CLUST_ALL4.1:

```{r, message='hide',warning='hide',results='hold',fig.asp=1,fig.width=4}

pheatmap(alldata@graphs$CCA_nn[1:200,1:200],
         col=c("white","black"),border_color = "grey90", main = "KNN graph",
         legend = F,cluster_rows = F,cluster_cols = F,fontsize = 2)

pheatmap(alldata@graphs$CCA_snn[1:200,1:200],
         col=colorRampPalette(c("white","yellow","red"))(100), 
         border_color = "grey90", main = "SNN graph",
         legend = F,cluster_rows = F,cluster_cols = F,fontsize = 2)
  
```

#CLUST_TITLE2.2:

#CLUST_ALL4.2:

#CLUST_SEURAT2:

```{r,results='hide',block.title=TRUE,fig.height=2.9,fig.width=10}
# Clustering with louvain (algorithm 1)
for (res in c( 0.1 , 0.25 , .5 , 1 , 1.5 , 2 )){
  alldata <- FindClusters(alldata, graph.name = "CCA_snn", resolution = res , algorithm = 1)
}

# each time you run clustering, the data is stored in meta data columns:
# seurat_clusters - lastest results only
# CCA_snn_res.XX - for each different resolution you test.

plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.0.5")+ggtitle("louvain_0.5"),
  DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.1")+ggtitle("louvain_1"),
  DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.2")+ggtitle("louvain_2")
)
```

#CLUST_ALL4.3:


```{r}
suppressPackageStartupMessages(library(clustree))

clustree(alldata@meta.data, prefix = "CCA_snn_res.")
```



#CLUST_TITLE3:

#CLUST_ALL7:

```{r,results='hide',block.title=TRUE,fig.height=2.9}
for (k in c( 5 , 7 , 10 , 12 , 15 , 17 , 20)){
  alldata@meta.data[,paste0("kmeans_",k)] <- kmeans(x = alldata@reductions[["pca"]]@cell.embeddings,
                                          centers = k,nstart = 100)$cluster
}

plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "umap", group.by = "kmeans_5")+ggtitle("kmeans_5"),
  DimPlot(alldata, reduction = "umap", group.by = "kmeans_10")+ggtitle("kmeans_10"),
  DimPlot(alldata, reduction = "umap", group.by = "kmeans_15")+ggtitle("kmeans_15")
)
```


```{r}

clustree(alldata@meta.data, prefix = "kmeans_")

```

#CLUST_TITLE4:

#CLUST_TITLE4.1:

#CLUST_ALL8.1:

```{r,results='hide',block.title=TRUE,fig.height=5}
d <- dist( alldata@reductions[["pca"]]@cell.embeddings,
           method="euclidean")
```

#CLUST_ALL8.2:

```{r,results='hide',block.title=TRUE,fig.height=5,fig.width=5}
#Compute sample correlations
sample_cor <- cor( Matrix::t(alldata@reductions[["pca"]]@cell.embeddings) )

#Transform the scale from correlations
sample_cor <- (1 - sample_cor) / 2

#Convert it to a distance object
d2 <- as.dist(sample_cor)
```

#CLUST_TITLE4.1:

#CLUST_ALL8.3:

```{r,results='hide',block.title=TRUE,fig.height=5,fig.width=10}
#euclidean
h_euclidean <- hclust(d, method="ward.D2")

#correlation
h_correlation <- hclust(d2, method="ward.D2")
```

#CLUST_ALL8.4:

```{r,results='hide',block.title=TRUE,fig.height=6}
#euclidean distance
alldata$hc_euclidean_5 <- cutree(h_euclidean,k = 5)
alldata$hc_euclidean_10 <- cutree(h_euclidean,k = 10)
alldata$hc_euclidean_15 <- cutree(h_euclidean,k = 15)

#correlation distance
alldata$hc_corelation_5 <- cutree(h_correlation,k = 5)
alldata$hc_corelation_10 <- cutree(h_correlation,k = 10)
alldata$hc_corelation_15 <- cutree(h_correlation,k = 15)


plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "umap", group.by = "hc_euclidean_5")+ggtitle("hc_euc_5"),
  DimPlot(alldata, reduction = "umap", group.by = "hc_euclidean_10")+ggtitle("hc_euc_10"),
  DimPlot(alldata, reduction = "umap", group.by = "hc_euclidean_15")+ggtitle("hc_euc_15"),

  DimPlot(alldata, reduction = "umap", group.by = "hc_corelation_5")+ggtitle("hc_cor_5"),
  DimPlot(alldata, reduction = "umap", group.by = "hc_corelation_10")+ggtitle("hc_cor_10"),
  DimPlot(alldata, reduction = "umap", group.by = "hc_corelation_15")+ggtitle("hc_cor_15")
)
```


#CLUST_ALL9:

```{r}
saveRDS(alldata,"data/results/covid_qc_dr_int_cl.rds")
```


#CLUST_ALL10:


#SESSION_INFO:

```{r}
sessionInfo()
```
