---
title: "Dimensionality reduction"
#CSS_ALL:
---


#DIMRED_MAIN:

#CHUNK_OPT:

#DIMRED_TITLE:

#DIMRED_ALL1:

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(cowplot)
  library(ggplot2)
  library(scran)
})

alldata <- readRDS("data/3pbmc_qc.rds")
```

#DIMRED_ALL1.1:

#DIMRED_ALL2:

```{r}
suppressWarnings(suppressMessages(alldata <- FindVariableFeatures(alldata, selection.method = "vst", nfeatures = 850,verbose = FALSE,assay = "RNA")))
top20 <- head(VariableFeatures(alldata), 20)

LabelPoints(plot = VariableFeaturePlot(alldata), points = top20, repel = TRUE)
```

#DIMRED_ALL3:

#DIMRED_ALL4:

```{r}
alldata <- ScaleData(alldata, vars.to.regress = "percent_mito", assay = "RNA")
```


#PCA_TITLE:

#PCA_ALL1:

```{r}
alldata <- RunPCA(alldata, npcs = 50, reduction.name = "PCA_on_RNA", assay = "RNA",verbose = F)
```

#PCA_ALL2:

```{r, fig.asp=.28}
plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "PCA_on_RNA", group.by = "orig.ident",dims = 1:2),
  DimPlot(alldata, reduction = "PCA_on_RNA", group.by = "orig.ident",dims = 3:4),
  DimPlot(alldata, reduction = "PCA_on_RNA", group.by = "orig.ident",dims = 5:6) )
```

#PCA_ALL3:

```{r,fig.asp=.5}
VizDimLoadings(alldata, dims = 1:5, reduction = "PCA_on_RNA",ncol = 5,balanced = T)
```


#PCA_ALL5:

```{r,fig.asp=.3}
ElbowPlot(alldata, reduction = "PCA_on_RNA",ndims = 50)
```

#PCA_ALL6:

#tSNE_TITLE:

#tSNE_ALL1:

```{r,fig.asp=1}
alldata <- RunTSNE(alldata, reduction = "PCA_on_RNA", dims = 1:30, reduction.name = "TSNE_on_RNA",
                   perplexity=30,
                   max_iter=1000,
                   theta=0.5,
                   eta=200,
                   num_threads=0 )
#see ?Rtsne and ?RunTSNE for more info
```

#tSNE_ALL2:

```{r,fig.asp=.28}
plot_grid(ncol = 3,DimPlot(alldata, reduction = "TSNE_on_RNA", group.by = "orig.ident"))
```


***
#UMAP_TITLE:

#UMAP_ALL1:

```{r}
alldata <- RunUMAP(alldata, reduction = "PCA_on_RNA", dims = 1:30,reduction.name = "UMAP_on_RNA",
                   n.components=2,
                   n.neighbors=30,
                   n.epochs=200,
                   min.dist=0.3,
                   learning.rate=1,
                   spread=1 )
#see ?RunUMAP for more info
```

#UMAP_ALL2:

```{r}
alldata <- RunUMAP(alldata, reduction.name = "UMAP10_on_RNA",
                   reduction = "PCA_on_RNA", 
                   dims = 1:30,
                   n.components=10,
                   n.neighbors=30,
                   n.epochs=200,
                   min.dist=0.3,
                   learning.rate=1,
                   spread=1 )
#see ?RunUMAP for more info
```

#UMAP_ALL2.1:

```{r,fig.asp=.28}
plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "UMAP_on_RNA", group.by = "orig.ident")+ ggplot2::ggtitle(label ="UMAP_on_RNA"),
  DimPlot(alldata, reduction = "UMAP10_on_RNA", group.by = "orig.ident",dims = 1:2)+ ggplot2::ggtitle(label ="UMAP10_on_RNA"),
  DimPlot(alldata, reduction = "UMAP10_on_RNA", group.by = "orig.ident",dims = 3:4)+ ggplot2::ggtitle(label ="UMAP10_on_RNA")
)
```

#UMAP_ALL2.2:

```{r,fig.asp=.28}
plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "PCA_on_RNA", group.by = "orig.ident"),
  DimPlot(alldata, reduction = "TSNE_on_RNA", group.by = "orig.ident"),
  DimPlot(alldata, reduction = "UMAP_on_RNA", group.by = "orig.ident")
)
```

#DIMRED_TITLE2:

#DIMRED_ALL5:

#DIMRED_ALL5.0:

#DIMRED_ALL5.1:

```{r}
alldata <- RunUMAP(alldata, reduction.name = "UMAP_on_ScaleData",
                   features = alldata@assays$RNA@var.features,
                   assay = "RNA",
                   n.components=2,
                   n.neighbors=30,
                   n.epochs=200,
                   min.dist=0.3,
                   learning.rate=1,
                   spread=1 )
```

#DIMRED_ALL5.2.1:

#DIMRED_ALL5.2:

```{r}
#Build Graph
alldata <- FindNeighbors(alldata,
                         reduction = "PCA_on_RNA",
                         graph.name = "SNN",
                         assay = "RNA",
                         k.param = 20,
                         features = alldata@assays$RNA@var.features)

#Run UMAP on a graph
alldata <- RunUMAP(alldata, reduction.name = "UMAP_on_Graph",
                   graph = "SNN",
                   assay = "RNA" )

```

#DIMRED_ALL5.3:

```{r, fig.asp=.28}
plot_grid(ncol = 3,
  DimPlot(alldata, reduction = "UMAP_on_RNA", group.by = "orig.ident")+ ggplot2::ggtitle(label ="UMAP_on_RNA"),
  DimPlot(alldata, reduction = "UMAP_on_ScaleData", group.by = "orig.ident")+ ggplot2::ggtitle(label ="UMAP_on_ScaleData"),
  DimPlot(alldata, reduction = "UMAP_on_Graph", group.by = "orig.ident")+ ggplot2::ggtitle(label ="UMAP_on_Graph")
)
```

#DIMRED_TITLE3:


#DIMRED_ALL6:

#MARKER_TABLE:

```{r,fig.asp=.9}
myfeatures <- c("CD3E","CD4","CD8A","NKG7","GNLY","MS4A1","CD14","LYZ","MS4A7","FCGR3A","CST3","FCER1A")
FeaturePlot(alldata, reduction = "UMAP_on_RNA",dims = 1:2,
            features = myfeatures,ncol = 3,order = T)
```


#DIMRED_ALL7:

```{r}
saveRDS(alldata,"data/3pbmc_qc_dr.rds")
```


#SESSION_INFO:

```{r}
sessionInfo()
```



