## conda requirements for all packages needed to run the scanpy tutorials
# install with:  mamba env create -f environment_scRNAseq2023.yml
# then run: source activate scRNAseq2023
name: scRNAseq2023

channels:
### MAIN CONDA CHANNELS ###
 - conda-forge
 - bioconda
 - defaults
### ADDITIONAL CONDA CHANNELS ###

dependencies:
### GENERAL LIBRARIES ###
 - r-base=4.1.3
 - rstudio-desktop=2022.12.0
 - wget
 - compilers
 - openssl
### R BIOCONDUCTOR PACKAGES ##
 - bioconductor-scater=1.22.0
 - bioconductor-scran=1.22.1
 - bioconductor-singlecellexperiment
 - bioconductor-slingshot
 - bioconductor-tradeseq
 - bioconductor-rhdf5
 - bioconductor-fgsea
 - bioconductor-biomart
 - bioconductor-org.hs.eg.db
 - bioconductor-scdblfinder
 - bioconductor-biocsingular
 - bioconductor-singler
 - bioconductor-batchelor
 - bioconductor-scmap
 - bioconductor-glmgampoi
 - bioconductor-scrnaseq
 - bioconductor-mast
 - bioconductor-dropletutils
 - bioconductor-scdblfinder 
### R CRAN PACKAGES ###
 - r-emdbook
 - r-rgl
 - r-plot3d
 - r-fastica
 - r-irlba
 - r-harmony
 - r-pheatmap
 - r-msigdbr
 - r-rafalib
 - r-enrichr
 - r-clustree
 - r-devtools
 - r-biocmanager
 - r-rcpphnsw
 - r-dplyr
 - r-igraph
 - r-seurat=4.3.0
 - r-umap
 - r-grr
 - r-hdf5r
 - r-bookdown
 - r-markdown
 - r-venn
 - r-uwot
 - r-optparse
 - r-fields
 - r-ggraph
 - r-checkmate
 - r-tidygraph
 - r-spam
 - r-stringi
 - r-stringr
 - r-pkgmaker
 - r-l1pack
 - r-nnls
 - r-reshape
 - r-jpeg
 - r-clustree
 - r-mlmetrics
 - r-caret
 - r-kernlab
 - r-proc
 - r-msigdbr
 - xbioc
# - r-scdc
 - r-scpred
 - r-harmony
 
### PYTHON LIBRARIES ###
 - multicore-tsne
 - umap-learn
 - scanorama


# Manual installation of packages that are not in conda:
# remotes::install_github('chris-mcginnis-ucsf/DoubletFinder', dependencies=FALSE)
# remotes::install_github('satijalab/seurat-data', dependencies=FALSE)
# remotes::install_github("meichendong/SCDC", dependencies = FALSE)



