name: scanpy_2024_nopip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - matplotlib-base
  - matplotlib-inline
  - numpydoc
  - seaborn
  - seaborn-base
  - urllib3
  - ipykernel
  - compilers
  - quarto
  - notebook
  - bbknn
  - geopandas
  - harmonypy
  - leidenalg
  - matplotlib-scalebar
  - matplotlib-venn
  - napari-matplotlib
  - numpy
  - pandas
  - pybiomart
  - scanpy
  - scikit-learn
  - scikit-misc
  - scrublet
  - celltypist
  - scarches
  - scvi-tools
  - scanorama
  - gseapy
  - fa2
  - pip:
    - fa2-modified  # obs, paga now needs fa2-modified package, not available as conda, need to install with pip.


#  - nb_conda_kernels  # skip, gives problem with neighbors
#  - jupyter_contrib_nbextensions  # skip, gives problem with neighbors
#  - traitlets<=5.9.0  # testing downgrade to see if it fixes issue with pp.neighbors crashing.


# Encountered problems while solving:
#  - package bbknn-1.6.0-py310he07d9a1_0 requires numpy >=1.26.2,<2.0a0, but none of the providers can be installed
#  - package scarches-0.6.1-pyh7e72e81_0 requires schpl >=1.0.0, but none of the providers can be installed
