name: seurat5
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - r-seurat=5.1.0
 - r-base=4.3.3
 - r-remotes
 - r-devtools
 - r-biocmanager
 - compilers
 - hdf5
 - cairo
 - quarto=1.3.450
 - r-quarto=1.3
 - r-hdf5r
 - r-cairo
 - r-harmony
 - r-r.utils
 - r-fields
 - r-clustree
 - r-arm
 - r-enrichr
 - r-msigdbr
 - r-scpred # perhaps remove if not working!
 - r-shinybs  # shiny for Azimuth
 - r-shinyjs
 - r-shinydashboard
 - r-googlesheets4
 - r-signac
# Bioconductor packages 
 - bioconductor-scran
 - bioconductor-scater
 - bioconductor-glmgampoi # for faster SCT
 - bioconductor-mast
 - bioconductor-fgsea
 - bioconductor-celldex 
 - bioconductor-singleR
 - bioconductor-tfbstools # for Azimuth
 - bioconductor-bsgenome.hsapiens.ucsc.hg38
 - bioconductor-jaspar2020
 - bioconductor-ensdb.hsapiens.v86
 - bioconductor-zellkonverter
 - bioconductor-complexheatmap
# for BioC labs
 - bioconductor-org.hs.eg.db
 - bioconductor-scdblfinder
 - r-umap
 - bioconductor-batchelor
 - bioconductor-scmap
# for trajectory
 - bioconductor-slingshot
 - bioconductor-tradeseq 
# for wrapup
# - r-vegan
 - r-mclust
 - bioconductor-deseq2
 - bioconductor-scry
# python packages 
 - umap-learn
 - scanorama




# with cairo need to use R4.3.3
# - r-seuratdisk - not compatible nothing provides icu 54.* needed by r-base-3.3.2-0


# remotes::install_github('chris-mcginnis-ucsf/DoubletFinder', dependencies=FALSE)
# remotes::install_github("satijalab/seurat-wrappers", "seurat5", dependencies=FALSE)
# remotes::install_github("immunogenomics/presto", dependencies = FALSE)
# remotes::install_github("mojaveazure/seurat-disk", dependencies = FALSE)
# remotes::install_github('satijalab/seurat-data', dependencies = FALSE)
# remotes::install_github("satijalab/azimuth", "seurat5", dependencies = FALSE)  