name: scanpy_2025
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.10.8
  - bbknn=1.6.0
  - celltypist=1.6.3
  - gseapy=1.1.3
  - harmonypy=0.0.10
  - ipykernel
  - jq
  - leidenalg=0.10.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - matplotlib-scalebar=0.8.1
  - matplotlib-venn=1.1.1
  - nbclient
  - nbformat
  - numpy=1.26.4
  - pandas=1.5.3
  - pip
  - pybiomart=0.2.0
  - python=3.10
  - python-igraph=0.11.6
  - scanorama=1.7.4
  - scanpy=1.10.3
  - scikit-learn
  - scipy=1.14.1
  - scrublet=0.2.3
  - scvi-tools=1.2.0
  - seaborn=0.13.2
