name: seurat_2025
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-basilisk=1.14.1
  - bioconductor-batchelor=1.18.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biomart=2.58.0
  - bioconductor-bluster=1.12.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.5
  - bioconductor-celldex=1.12.0
  - bioconductor-edger=4.0.16
  - bioconductor-ensdb.hsapiens.v86=2.99.0
  - bioconductor-fgsea=1.28.0
  - bioconductor-glmgampoi=1.14.0
  - bioconductor-jaspar2020=0.99.10
  - bioconductor-mast=1.28.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-scater=1.30.1
  - bioconductor-scdblfinder=1.16.0
  - bioconductor-scmap=1.24.0
  - bioconductor-scran=1.30.0
  - bioconductor-singler=2.4.0
  - bioconductor-slingshot=2.10.0
  - bioconductor-sparsematrixstats=1.14.0
  - bioconductor-tfbstools=1.40.0
  - bioconductor-tradeseq=1.16.0
  - jq
  - r-base=4.3.3
  - r-clustree=0.5.1
  - r-dplyr=1.1.4
  - r-enrichr=3.2
  - r-fields
  - r-googlesheets4=1.1.1
  - r-harmony=1.2.1
  - r-hdf5r=1.3.11
  - r-lme4=1.1_35.5
  - r-msigdbr=7.5.1
  - r-pheatmap=1.0.12
  - r-remotes=2.5.0
  - r-scpred=1.9.2
  - r-seurat=5.1.0
  - r-shinybs=0.61.1
  - r-shinydashboard=0.7.2
  - r-shinyjs=2.1.0
  - r-signac=1.14.0
  - r-umap=0.2.10.0
  - scanorama=1.7.4
  - umap-learn=0.5.3
