[workspace]
authors = ["Susanne Reinsbach <susanne.reinsbach@scilifelab.se>"]
channels = ["conda-forge", "bioconda"]
name = "scanpy-2026"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
anndata = ">=0.12.10,<0.13"
bbknn = ">=1.6.0,<2"
cellrank = ">=2.0.7,<3"
celltypist = ">=1.7.1,<2"
fa2_modified = "==0.4"
gseapy = ">=1.1.11,<2"
harmonypy = ">=0.2.0,<0.3"
ipykernel = ">=7.2.0,<8"
leidenalg = ">=0.11.0,<0.12"
matplotlib-base = ">=3.10.8,<4"
matplotlib-inline = ">=0.2.1,<0.3"
matplotlib-scalebar = ">=0.9.0,<0.10"
matplotlib-venn = ">=1.1.2,<2"
nbclient = ">=0.10.4,<0.11"
nbformat = ">=5.10.4,<6"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
pip = ">=26.0.1,<27"
pybiomart = ">=0.2.0,<0.3"
python = ">=3.12.12,<3.13"
python-igraph = ">=1.0.0,<2"
scanorama = ">=1.7.4,<2"
scanpy = ">=1.12,<2"
scikit-learn = "<1.5"
scipy = ">=1.16.3,<2"
scrublet = ">=0.2.3,<0.3"
scvi-tools = ">=1.4.1,<2"
seaborn = ">=0.13.2,<0.14"
